/*
 * Copyright 2015 Enamul.
 *
 * Most of my softwares are open for educational purpose, but some are 
 * confidential. So, before using it openly drop me some lines at
 *
 *      enamsustcse@gmail.com
 *
 * I do not guarantee that the software would work properly. There could
 * remain bugs. If you found any of them, kindly report me.
 * If you need to use this or some part of it, use it at your own risk.
 * This software is not a professionally developed, so commercial use 
 * is not approved by default.
 */
package contest;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Enamul
 */
public class ShowCode extends javax.swing.JDialog {
    Submission submission;
    Contest contest;
    int submissionNo;
    /**
     * Creates new form ShowCode
     */
    public ShowCode(JDialog parent, Submission submission,Contest contest,int submissionNo) {
        super(parent, true);
        initComponents();
        
        this.submission = submission;
        this.contest = contest;
        this.submissionNo = submissionNo;
        
        initiateAll();
        writeCode();
        
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                parent.setVisible(true);
                setVisible(false);
                dispose();
            }
        });

        //adjust screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();
        setLocation((int) Math.max((width - getWidth()) / 2, 0), (int) Math.max((height - getHeight()) / 2, 0));

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    void writeCode(){
        jTextAreaCode.setEditable(false);
        jTextAreaCode.setText("");
        BufferedReader reader = null;
        try {
            // TODO add your handling code here:
            File toRead = submission.submittedFile;
            reader = new BufferedReader(new FileReader(toRead));
            String now = reader.readLine();

            while (now != null) {
                jTextAreaCode.append(now+"\n");
                now = reader.readLine();
            }

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Opps!\nIt seems the source code has been moved somewhere else or been deleted!\nFile: "+submission.submittedFile.toString(), "File Not Found!", JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(ContestSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
                        jButtonBackActionPerformed(null);
//            Logger.getLogger(ContestSetting.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                reader.close();
            } catch (IOException ex) {
//                Logger.getLogger(ContestSetting.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    
    void initiateAll(){
        String timeFormat = String.format("%02d:%02d:%02d", submission.timePassed / 3600, (submission.timePassed / 60) % 60, submission.timePassed % 60);
                    
        jLabelSubmissionNumber.setText(String.format("%d",submissionNo+1));
        jLabelUser.setText(submission.user);
        jLabelVerdict.setText(submission.verdict);
        jLabelLanguage.setText(submission.language);
        jLabelProblemName.setText(contest.problems[submission.problemId-1].problemName);
        jLabelContestTime.setText(timeFormat);
        jLabelDate.setText(String.format("%s", submission.date));
        jLabelFilePath.setText(submission.submittedFile.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCode = new javax.swing.JTextArea();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelSubmissionNo = new javax.swing.JLabel();
        jLabelSubmissionNumber = new javax.swing.JLabel();
        jLabelSubmissionNo1 = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelLanguage = new javax.swing.JLabel();
        jLabelSubmissionNo2 = new javax.swing.JLabel();
        jLabelSubmissionNo3 = new javax.swing.JLabel();
        jLabelProblemName = new javax.swing.JLabel();
        jLabelSubmissionNo4 = new javax.swing.JLabel();
        jLabelFilePath = new javax.swing.JLabel();
        jLabelVerdict = new javax.swing.JLabel();
        jLabelSubmissionNo5 = new javax.swing.JLabel();
        jLabelSubmissionNo6 = new javax.swing.JLabel();
        jLabelContestTime = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelSubmissionNo7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextAreaCode.setColumns(20);
        jTextAreaCode.setRows(5);
        jTextAreaCode.setToolTipText("");
        jScrollPane1.setViewportView(jTextAreaCode);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Submitted Code");

        jLabelSubmissionNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubmissionNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSubmissionNo.setText("Submission No: ");

        jLabelSubmissionNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubmissionNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSubmissionNumber.setText("0000");

        jLabelSubmissionNo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubmissionNo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSubmissionNo1.setText("Submitted By:");

        jLabelUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelUser.setText("username");

        jLabelLanguage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelLanguage.setText("C++");

        jLabelSubmissionNo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubmissionNo2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSubmissionNo2.setText("Language: ");

        jLabelSubmissionNo3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubmissionNo3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSubmissionNo3.setText("Problem Name:");

        jLabelProblemName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProblemName.setText("Problem Name");

        jLabelSubmissionNo4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubmissionNo4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSubmissionNo4.setText("File Path: ");

        jLabelFilePath.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelFilePath.setText("File path");

        jLabelVerdict.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelVerdict.setText("AC");

        jLabelSubmissionNo5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubmissionNo5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSubmissionNo5.setText("Verdict:");

        jLabelSubmissionNo6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubmissionNo6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSubmissionNo6.setText("Contest Time:");

        jLabelContestTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelContestTime.setText("at time");

        jLabelDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDate.setText("Date");

        jLabelSubmissionNo7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubmissionNo7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSubmissionNo7.setText("Date:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSubmissionNo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSubmissionNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSubmissionNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSubmissionNo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSubmissionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLanguage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelSubmissionNo1)
                                    .addComponent(jLabelSubmissionNo3)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelContestTime, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelSubmissionNo7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelProblemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelSubmissionNo5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVerdict, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSubmissionNo)
                    .addComponent(jLabelSubmissionNumber)
                    .addComponent(jLabelSubmissionNo1)
                    .addComponent(jLabelUser)
                    .addComponent(jLabelSubmissionNo5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVerdict))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelSubmissionNo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelLanguage)
                        .addComponent(jLabelProblemName)
                        .addComponent(jLabelSubmissionNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSubmissionNo6)
                    .addComponent(jLabelContestTime)
                    .addComponent(jLabelSubmissionNo7)
                    .addComponent(jLabelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSubmissionNo4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ShowCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ShowCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ShowCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ShowCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ShowCode dialog = new ShowCode(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContestTime;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelFilePath;
    private javax.swing.JLabel jLabelLanguage;
    private javax.swing.JLabel jLabelProblemName;
    private javax.swing.JLabel jLabelSubmissionNo;
    private javax.swing.JLabel jLabelSubmissionNo1;
    private javax.swing.JLabel jLabelSubmissionNo2;
    private javax.swing.JLabel jLabelSubmissionNo3;
    private javax.swing.JLabel jLabelSubmissionNo4;
    private javax.swing.JLabel jLabelSubmissionNo5;
    private javax.swing.JLabel jLabelSubmissionNo6;
    private javax.swing.JLabel jLabelSubmissionNo7;
    private javax.swing.JLabel jLabelSubmissionNumber;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelVerdict;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCode;
    // End of variables declaration//GEN-END:variables
}
